/*
 * This source file was generated by the Gradle 'init' task
 */
package Proyecto.games.Common_files;

import java.awt.Graphics2D;

import javax.swing.JFrame;
import javax.swing.JPanel;  


abstract class GameLoop {
    private boolean runFlag = false;

    public void run(double delta) {
        runFlag = true;
        startup();
        while (runFlag) {
            update(delta);
            draw();
        }
        shutdown();
    }

    public void stop() {
        runFlag = false;
    }

    public abstract void startup();
    public abstract void shutdown();
    public abstract void update(double delta);
    public abstract void draw();
}



public abstract class JGame extends GameLoop {
    final private JFrame frame;
    private JPanel canvas;
    protected Graphics2D g;
    final private int winModeWidth, winModeHeight;

    public JGame(String title, int width, int height) {
        this.winModeWidth = width;
        this.winModeHeight = height;
        frame = new JFrame(title);
        canvas = new JPanel();
        frame.add(canvas);
    }

    @Override
    public void startup() {
        gameStartup();
    }

    @Override
    public void update(double delta) {
        gameUpdate(delta);
    }

    @Override
    public void draw() {
        Graphics2D g2 = (Graphics2D) canvas.getGraphics();
    if (g2 != null) {
        gameDraw(g2);
        g2.dispose();
    }
    }

    @Override
    public void shutdown() {
        gameShutdown();
    }

    public abstract void gameStartup();
    public abstract void gameUpdate(double delta);
    public abstract void gameDraw(Graphics2D g);
    public abstract void gameShutdown();
    protected abstract void ReadPropertiesFile();
    
    // Getters for frame and canvas for each game view manager 
    public JFrame getFrame() {
        return this.frame;
    }
    public JPanel getCanvas() {
        return this.canvas;
    }
    public int getWidth() {
        return this.winModeWidth;
    }
    public int getHeight() {
        return this.winModeHeight;
    }
}
