# NIVEL 1
lvl1.levelNumber = 1
lvl1.exitX = 1020
lvl1,exitY = 300
lvl1,spawnerX = 690
lvl1.spawnerY = 70
lvl1.lemmingsToGenerate = 3
lvl1.percentajeToWin = 0.33
lvl1.title = "Just Digging"
lvl1.stock.digger = 5
lvl1.stock.climb = 0
lvl1.stock.stop = 3
lvl1.stock.umbrella = 0

# NIVEL 2
lvl2.levelNumber = 2;
lvl2.exitX = 1100;
lvl2.exitY = 340;
lvl2.spawnerX = 400;
lvl2.spawnerY = 30;
lvl2.lemmingsToGenerate = 3;
lvl2.percentageToWin = 1.0;
lvl2.title = "Float to Freedom";
lvl2.stock.digger = 0;
lvl2.stock.climb = 0;
lvl2.stock.stop = 0;
lvl2.stock.umbrella = 3;


# NIVEL 3
lvl3.levelNumber = 3;
lvl3.exitX = 1050;
lvl3.exitY = 260;
lvl3.spawnerX = 410;
lvl3.spawnerY = 200;
lvl3.lemmingsToGenerate = 5;
lvl3.percentageToWin = 0.8;
lvl3.title = "Climbers' Canyon";
lvl3.stock.digger = 0;
lvl3.stock.climb = 10;
lvl3.stock.stop = 2;
lvl3.stock.umbrella = 10;
