#Configuraciones actualizadas
#Wed Aug 06 14:48:40 ART 2025
difficult=2
isFullscreen=false
isVersusIA=true
maxPoints=3
musicOff=false
player1.down=S
player1.up=W
player2.down=L
player2.up=O
skin.ball=0
skin.pitch=1
track=2
