# Dificultad del juego: EASY, MIDDLE o HARD
difficult=2

# Puntaje máximo antes de terminar la partida
maxPoints=10

# Música activada o desactivada
musicOff=false

# Pantalla completa
isFullscreen=false

# Teclas de movimiento jugador 1
player1.up=W
player1.down=S

# Teclas de movimiento jugador 2
player2.up=O
player2.down=L

# ¿Jugador contra la máquina?
isVersusIA=true

# Skins disponibles cancha: DEFAULT O BASKET
skin.pitch=1

# Skins disponibles pelota: DEFAULT O CRAZY
skin.ball=0
