#Configuraciones actualizadas
#Tue Aug 05 18:09:57 ART 2025
difficult=2
isFullscreen=false
isVersusIA=false
maxPoints=1
musicOff=true
player1.down=S
player1.up=W
player2.down=L
player2.up=O
skin.ball=0
skin.pitch=0
track=2
