/*
 * This source file was generated by the Gradle 'init' task
 */
package Proyecto;

import java.awt.Graphics2D;

public class App {
    public static void main(String[] args) {
        
    }
}


abstract class GameLoop{
    private boolean runFlag = false;
    public void run(){
    runFlag = true;
    startup();
    while(runFlag){
    update();
    draw();
    }
    shutdown();
    }
    public void stop(){
    runFlag = false;
    }
    public abstract void startup();
    public abstract void shutdown();
    public abstract void update();
    public abstract void draw();
    }

abstract class JGame extends GameLoop{
        public JGame(String title, int width, int height){
        }
        @Override public void startup(){
            gameStartup();
        }
        public void update(double delta){
            gameUpdate(delta);
        }
        @Override public void draw(){}
        @Override public void shutdown(){ gameShutdown(); }
        public abstract void gameStartup();
        public abstract void gameUpdate(double delta);
        public abstract void gameDraw(Graphics2D g);
        public abstract void gameShutdown();
        protected void readPropertiesFile(){
        
        }
        }

//extends class JGame

class Pong{

    public void gameStartup(){};
    public void gameUpdate(double delta){};
    public void gameDraw(Graphics2D g){};
    public void gameShutdown(){};
    Pong(){};
}


class Lemmings{
    public void gameStartup(){};
    public void gameUpdate(double delta){};
    public void gameDraw(Graphics2D g){};
    public void gameShutdown(){};
    Lemmings(){};
}



