/*
 * This source file was generated by the Gradle 'init' task
 */
package proyecto;

import org.junit.jupiter.api.Test;

import Proyecto.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
